### ISSUE TITLE
Prettify function parameters?

### ISSUE THREAD

**Issue by bluefangs** [klaseskilson/meteor-black-box#1]
Hi,
I just wanted to know if there is a mechanism to show function parameters in a structured manner, specially when the parameter is an object.

Thanks.

**Comment by klaseskilson** [comment]
Hi,
I suggested you fork this project and publish your own fork if you want to do that. What I believe you're asking for could for instance be achieved by replacing `args` on [these lines](https://github.com/klaseskilson/meteor-black-box/blob/7953de291d1a13b02c6b2df917fe82fd39a90a57/black-box.js#L13-L20) with `JSON.stringify(args)` or something similar.

Best of luck.

**Comment by bluefangs** [comment]
Appriciate the quick hint. Thanks!
